---
train:
  model:
    model_name: "swin"
    image_size: 224
    patch_size: 4
    num_classes: 2
    embed_dim: 128
    depths: [ 2, 2, 18, 2 ]
    num_heads: [ 4, 8, 16, 32 ]
    window_size: 7
    drop_rate: 0
    drop_path_rate: 0.1
    in_chans: 3
  params:
    image_size: [224,224,224,224]
    batch_size: 128
    epoch: 10
    lr: 0.00001
    decay: 0.1
    decay_step:
      - 2
  save:
    save_path: "/home/work/didonglin/Gaze-PrecClk/Gaze-tf"
    model_name: "swin"
    step: 2
  data:
    # image: '/disk1/repository/p30pro_shape/Image'
    # label: '/disk1/repository/p30pro_shape/Label'
    image: '/disk1/repository/GazeCapture_2D/Image'
    label: '/disk1/repository/GazeCapture_2D/Label/train'
    # image: '/disk1/repository/p30pro_shape/Image'
    # label: '/disk1/repository/p30pro_shape/Label'
  pretrains: "None"
test:
   load:
      begin_step: 8
      end_step: 10
      steps: 2
      model_name: "swin"
      load_path: "/home/work/didonglin/Gaze-PrecClk/Gaze-tf"
   data:
    image: '/disk1/repository/GazeCapture_2D/Image'
    label: '/disk1/repository/GazeCapture_2D/Label/test'
reader: gazecapturef
